### ISSUE TITLE
v2decoder does not set the NucleicAcidPart grid_type property

### ISSUE THREAD

**Issue by cmaffeo** [cadnano/cadnano2.5#106]
The v2decoder correctly detects lattice type, but it does not set the 'grid_type' property in the newly created NucleicAcidPart. 

The result is that a square lattice object loaded through the v2decoder appears over a honeycomb grid, requiring the user to manually change the grid_type. See the left panel below.
<img width="600" alt="screen shot 2017-03-27 at 12 00 13 pm" src="https://cloud.githubusercontent.com/assets/15238540/24376137/6f792fbe-1300-11e7-8233-7e382bf3d3ee.png">

**Comment by sdouglas** [comment]
This will be fixed in our next release

**Comment by nickfong** [comment]
This should be implemented as of the most recent changes on `master`.  

@cmaffeo Thanks for the bug report; please re-open this issue if you're still seeing this behavior on the most up-to-date version on `master`
