### ISSUE TITLE
lattice type is not saved

### ISSUE THREAD

**Issue by dave-doty** [cadnano/cadnano2.5#113]
The default lattice is honeycomb. This can be edited to be square by selecting from a drop-down list in the bottom-right panel, but this value is not saved, so if the file is saved, and re-opened, the honeycomb lattice returns.

**Comment by nickfong** [comment]
Hi @dave-doty, 

Thanks for the bug report.  This issue should be fixed in the upcoming release.  

Cheers,
Nick

**Comment by nickfong** [comment]
This should be implemented as of the most recent changes on `master`.  

@dave-doty Thanks again for the bug report; please re-open this issue if you're still seeing this behavior on the most up-to-date version on `master`
