### ISSUE TITLE
Views buttons on GUI should be "clicked" by default

### ISSUE THREAD

**Issue by pfdamasceno** [cadnano/cadnano2.5#154]
In 2.5.2.1 (v3io-fix branch) the default behavior when launching cadnano's GUI is that all 3 panel views are shown. Yet the last 2 buttons are not 'clicked' (see below)

![screen shot 2018-02-08 at 9 12 53 am](https://user-images.githubusercontent.com/6766193/35987348-4673255c-0cb0-11e8-9cbd-cff20ea6b6ba.png)

**Comment by sdouglas** [comment]
This is fixed in my pending PR #148

**Comment by nickfong** [comment]
#148 was merged and this issue is verified as being fixed on `master`
