### ISSUE TITLE
Can’t open the cadnano

### ISSUE THREAD

**Issue by George-dle** [cadnano/cadnano2.5#183]
I installed cadnano ，however I can't open it 。And I try some methods ，such as 

![image](https://user-images.githubusercontent.com/64884607/81139642-0aab7b00-8f99-11ea-8b6e-8a3d87758746.png)
However，the result doesn't change.
![image](https://user-images.githubusercontent.com/64884607/81139699-447c8180-8f99-11ea-81b4-300f6f470ed8.png)
So could guys can give me some suggestions?

**Comment by sdouglas** [comment]
We primarily use cadnano2.5 for scripting with the Python API. You might try earlier versions for designing with the GUI. See [these tutorials](http://douglaslab.org/tutorials/) for installation instructions.
