### ISSUE TITLE
Saving cadnano "json" files in the "old" format

### ISSUE THREAD

**Issue by joelhochstetter** [cadnano/cadnano2.5#184]
I've recently updgraded to cadnano2.5 after previously working with cadnano1 and  cadnano2. I've noticed that the json save file structure has changed for this edition. However, I've written various scripts manipulating the json files using the old save format that are now incompatible with the new format.

Is it possible to save designs in the "old" json format within cadnano2.5, or do I need to change back to using an older version of cadnano?

**Comment by sdouglas** [comment]
Yes, just pass the argument `legacy=True` when you export the file:
https://github.com/cadnano/cadnano2.5/blob/ce6ff019b88ee7728de947bd86b35861cf57848d/cadnano/document.py#L223

**Comment by joelhochstetter** [comment]
> Yes, just pass the argument `legacy=True` when you export the file:
> https://github.com/cadnano/cadnano2.5/blob/ce6ff019b88ee7728de947bd86b35861cf57848d/cadnano/document.py#L223

Thanks for the help Shawn!
