### ISSUE TITLE
cannot install on Mac

### ISSUE THREAD

**Issue by totoropian** [cadnano/cadnano2.5#185]
Hi, I tried to install Cadnano 2.2 on my new computer, but it appeared "The package is trying to install content to the system volume. Contact the software manufacturer for assistance". Thank you.

**Comment by totoropian** [comment]
The package is trying to install content to the system volume. Contact the software manufacturer for assistance.

**Comment by sdouglas** [comment]
Here are the steps we currently use to install Cadnano GUI versions (1 and 2): http://douglaslab.org/tutorials/
