### ISSUE TITLE
Isolate non-gui tests for depencency-free continuous integration

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#29]
The following should be a good point to merge `testdev` back into dev
1. port current tests (wherever possible) to run without initializing the qApp
2. create travis.yml config to run free hosted CI
3. preserve some gui tests for local testing

Future enhancements (beyond the scope of this issue)
- Set up our own test server with necessary dependencies, and start using [QTest](https://qt-project.org/doc/qt-5-snapshot/qtest-overview.html) framework for GUI tests.

**Comment by grinner** [comment]
non gui tests now work
