### ISSUE TITLE
add setup.py

### ISSUE THREAD

**Issue by grinner** [cadnano/cadnano2.5#38]
Since this works so well in Anaconda, maybe a setup.py is worth having

**Comment by grinner** [comment]
We need wheels for pyqt5

**Comment by scholer** [comment]
For the record, to install pyqt5 with anaconda:

First create a new conda environment. The default anaconda install typically have pyqt4 installed, and that doesn't always play well with pyqt5, so we need to create an empty one. (If you know what you are doing, you can omit the ```--no-default-packages``` flag.) 

    conda create --no-default-packages -n pyqt5 python=3

followed by 

    activate pyqt5

Second, install pyqt5 in the new environment. (Make sure you have activated the pyqt5 environment using the ```activate``` command). Unfortunately, Anaconda doesn't have an official pyqt5 build at the moment, but [dsdale24 has 64-bit Win/OSX/Linux builds on his channel](https://anaconda.org/dsdale24/pyqt5). Install this using 

    conda install -c https://conda.anaconda.org/dsdale24 pyqt5

*Note:* Before doing the step above, you may want to check if an official Anaconda pyqt5 build is available. You can check this simply using  ```conda search pyqt5``` or ```conda install pyqt5```.

**Comment by scholer** [comment]
Update: dsdale24's pyqt5 doesn't work with python 3.5; it was build for python 3.4.
There's two ways to prevent this from causing errors during install:

(a) Make sure your ```pyqt5``` env uses python 3.4 (NOT python 3.5 or higher). You can do this when creating the environment by:

    conda create --no-default-packages -n pyqt5 python=3.4

(b) Using a PyQt5 build for python 3.5. For instance, inso has a build for Windows (32/64) and Linux (64), which can be installed with:

    conda install -c https://conda.anaconda.org/inso pyqt5

**Comment by grinner** [comment]
README updated
