### ISSUE TITLE
FR: Official plugin repository

### ISSUE THREAD

**Issue by scholer** [cadnano/cadnano2.5#46]
##### Feature request: Official plugin repository

The plugin feature of cadnano is potentially really powerful and could allow cadnano to be extended with many custom features without bloating the main software base. 
However, to date, very few cadnano plugin have been published.

Is the plugin feature something that we will continue to support? If so, maybe it would be nice to have a sort of official list/repository with plugins. This would make plugins easier to find, which would also make it easier for potential new plugin developers to learn how to create cadnano plugins.

A first step could simply be a curated page/file in markdown format. If it ever becomes relevant, this could then form the basis for an actual plugin repository (e.g. something like [this](https://github.com/wbond/package_control_channel)).

**Comment by grinner** [comment]
Do you have time to meet tomorrow to discuss there features and future cadnano 2.5 work?

**Comment by grinner** [comment]
Due to the official API nature of cadnano, we will be doing a "plugin" repo, and we will provide some examples of doing it in the API style.  New repo is coming soon
