### ISSUE TITLE
Fix interact mode

### ISSUE THREAD

**Issue by grinner** [cadnano/cadnano2.5#55]
This is a major enhancement to get something that will work with the Qt Event loop

**Comment by scholer** [comment]
For the record, interactive mode *does* work (Windows), but it is rather slow - there is a significant delay when typing in the interactive interpreter.

**Comment by grinner** [comment]
This still works great on OS X, but the whole ObjectInstance thing is causing issues for me, so we need to get ObjectInstance.reference() instead.
