### ISSUE TITLE
click and drag endpointitem with AltModifier causes error

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#65]
Holding the AltModifier (Option key on mac) when doing a left mouseclick on an EndpointItem automatically extends it to its drag boundary. This is intended as a timesaving trick.

However, click+dragging with AltModifier somehow attempts to resize further than true the boundary, probably by doing two resize operations in serial.

![image](https://cloud.githubusercontent.com/assets/45583/11008563/291ed79e-8486-11e5-97d7-d0aa125846a5.png)

**Comment by grinner** [comment]
You're assumption appears to be correct according to the undo stack

**Comment by grinner** [comment]
disabled behavior for now
