### ISSUE TITLE
sliceview vhi arrow angle might be adjusted

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#69]
I usually try to choose an angle that splits the difference between two neighboring crossovers, since that probably matches reality a bit better in an actual nanostructure. The current angles may give a false impression if half of a crossover lines up perfectly, and the other half puts the phosphates several angstroms apart.

Compare the 1-2 crossover below with the angles of the slice red arrows for helix 1 & 2
![009](https://cloud.githubusercontent.com/assets/45583/11378304/5d5a5ebc-929f-11e5-8b1f-f796a837e294.jpg)

Likewise for 0-1 crossover:
![010](https://cloud.githubusercontent.com/assets/45583/11378306/6022088e-929f-11e5-91c7-7b17e11c09be.jpg)

**Comment by grinner** [comment]
fixed, but prexovers for Honeycombs are tweaked slightly from CN2
