### ISSUE TITLE
AttributeError: 'DocumentWindow' object has no attribute

### ISSUE THREAD

**Issue by thomsen3** [cadnano/cadnano2.5#75]
Hi, I am having trouble opening cadnano2.5 as I get an attributeerror in ubuntu 14, This is error message. Any clues?

rt_ubuntu@UbuntuRT:~/cadnano2.5$ 
rt_ubuntu@UbuntuRT:~/cadnano2.5$ python3 pyqt5_check.py 
Import success! No need to do anything
rt_ubuntu@UbuntuRT:~/cadnano2.5$ python3 bin/main.py
['bin/main.py']
the doc <cadnano.document.Document object at 0x7f873b3af5e8>
Traceback (most recent call last):
  File "bin/main.py", line 44, in <module>
    main(sys.argv)
  File "bin/main.py", line 24, in main
    app = initAppWithGui(args)
  File "./cadnano/__init__.py", line 38, in initAppWithGui
    shared_app.finishInit()
  File "./cadnano/cadnanoqt.py", line 66, in finishInit
    self.d = self.newDocument(base_doc=doc)
  File "./cadnano/cadnanoqt.py", line 138, in newDocument
    dc = DocumentController(base_doc)
  File "./cadnano/gui/controllers/documentcontroller.py", line 48, in __init__
    self._initWindow()
  File "./cadnano/gui/controllers/documentcontroller.py", line 53, in _initWindow
    self.win = DocumentWindow(doc_ctrlr=self)
  File "./cadnano/gui/views/documentwindow.py", line 41, in __init__
    self.setupUi(self)
  File "./cadnano/gui/ui/mainwindow/ui_mainwindow.py", line 24, in setupUi
    MainWindow.setUnifiedTitleAndToolBarOnMac(True)
AttributeError: 'DocumentWindow' object has no attribute 'setUnifiedTitleAndToolBarOnMac'

**Comment by grinner** [comment]
I haven't seen this in my linux testing.  How did you install Qt5 and PyQt5?

**Comment by thomsen3** [comment]
I installed Qt5 according to this: https://wiki.qt.io/Install_Qt_5_on_Ubuntu
and PyQt5 by calling these:
sudo apt-get install libqt5webkit5-dev
sudo apt-get install python3-pyqt5.qtsvg
sudo apt-get install python3-pyqt5.qtwebkit

But when i try to install PyQt5 through http://pyqt.sourceforge.net/Docs/PyQt5/installation.html
It seems like the qmake does not use the Qt5
rt_ubuntu@UbuntuRT:~/Documents/Python/PyQt-gpl-5.5.1$ python3 configure.py
Querying qmake about your Qt installation...
Error: PyQt5 requires Qt v5.0 or later. You seem to be using v4.8.6. Use the
--qmake flag to specify the correct version of qmake.

and know i am looking into changing this as
rt_ubuntu@UbuntuRT:~/Documents/Python/PyQt-gpl-5.5.1$ qmake --version
QMake version 2.01a
Using Qt version 4.8.6 in /home/rt_ubuntu/anaconda/lib

Do you know a quick way of doing this then?

**Comment by grinner** [comment]
try using the built in pyqt5_check.py per the README
