### ISSUE TITLE
add linux installation guide

### ISSUE THREAD

**Issue by antonkulaga** [cadnano/cadnano2.5#76]
Please, add linux installation guide. Right now it has only PC and MacOS ones

**Comment by grinner** [comment]
Please refer to the line "Mac and Linux" in the `README.md`. the `dev` branch has a more up to date version of the `README.md` than `master`

https://github.com/cadnano/cadnano2.5/blob/dev/README.md

cadnano2.5 is currently under heavy development, and while master is stable, we will get to updating master soon with many new features.
