### ISSUE TITLE
[dev branch] Can't export an opened .json file to .csv

### ISSUE THREAD

**Issue by hadim** [cadnano/cadnano2.5#90]
I know you are working on the new cadnano version on the `master` branch but here we are still using the `dev` branch waiting to have `master` more stable.

It's possible to export an origami when we create it from the software but when we open an origami from a .json file, cadnano crash when the Export button is clicked with the following error : 

```
Test plugin loaded, has access to cadnano: <module 'cadnano' from './cadnano/__init__.py'>
partAddedSlot:  <HoneycombPart 0904> HoneycombPart
Traceback (most recent call last):
  File "./cadnano/gui/controllers/documentcontroller.py", line 330, in actionExportSequencesSlot
    stap_loop_olgs = part.getStapleLoopOligos()
AttributeError: 'ObjectInstance' object has no attribute 'getStapleLoopOligos'
```
It looks like when a file is opened `ObjectInstance` is not the same as when the origami is created in the current session in the software.

So I have commented the part using `getStapleLoopOligos` in `actionExportSequencesSlot` but another error appears : 

```
Test plugin loaded, has access to cadnano: <module 'cadnano' from './cadnano/__init__.py'>
partAddedSlot:  <HoneycombPart 9672> HoneycombPart
Traceback (most recent call last):
  File "./cadnano/gui/controllers/documentcontroller.py", line 560, in exportStaplesCallback
    output = self.activePart().getStapleSequences()
AttributeError: 'ObjectInstance' object has no attribute 'getStapleSequences'
```

It looks like again the `ObjectInstance` because it's different doesn't have all the correct methods/attributes.

Maybe the IO process when opening a .json file is missing something ?

Could you help us with that ? I can do some more investigations/fix if you point me to the correct direction.

Thank you for your time.

**Comment by grinner** [comment]
I'm looking into it now

**Comment by grinner** [comment]
try this commit.  Seems to work for me.  This issue got addressed in `master` as there were a ton of issues related to `ObjectInstance`s that came up.

**Comment by grinner** [comment]
Incidentally, we are trying to officially announce Beta on `master` by Friday.   Just hammering out some API issues for our's and others sanity sake.

**Comment by hadim** [comment]
Thanks I'll try that soon. 

I have also found a small PyQt bug in the dev branch using PyQt from pypi (i am still waiting for PyQt5 in conda-forge). I'll submit a PR against the dev branch. 

(maybe you should rename the dev branch to 'legacy'  to not confuse people) 

Thanks again

**Comment by grinner** [comment]
We totally understand things are confusing, but they should settle on Friday.  What's the PyQt5 version?  I had problems with 5.6, but not 5.7.

**Comment by hadim** [comment]
I confirm the fix works.

I have made a PR against `dev` to fix the PyQt bug I've found : https://github.com/cadnano/cadnano2.5/pull/91
