### ISSUE TITLE
Bugs when cutting an oligo

### ISSUE THREAD

**Issue by hadim** [cadnano/cadnano2.5#98]
We have tried the new version and it works well for us. But we have noticed small bugs happening when cutting an oligo.

To reproduce : 

- Open whatever design you have
- Cut an oligo with the "Break" tool on two points : 3 oligos should be created from the original one

We have noticed they all have the same names and when we change the color, it is not reflected on the design.

Also if you click on the checkbox of that oligo two times, the color used for this oligo is always red.

Last thing : we can't modify the `max_vhelix_length` value (while it was possible in the previous version. For now we are modifying it directly in the JSON file.

**Comment by hadim** [comment]
Ping @sdouglas

**Comment by grinner** [comment]
I think I fixed this with e8e1bd5
