### ISSUE TITLE
Can't set the name of the scaffold strand oligo

### ISSUE THREAD

**Issue by hadim** [cadnano/cadnano2.5#99]
An error is raised when changing the name of the scaffold strand oligo in the bottom right properties box : 

```
  File "c:\users\john\anaconda3\envs\cadnano\lib\site-packages\cadnano\gui\views
\propertyview\oligoitem.py", line 50, in oligoPropertyChangedSlot
    if model_oligo in self._cn_model_set:
AttributeError: 'OligoSetItem' object has no attribute '_cn_model_set'
```

Configuration is : Windows, Python 3.5 (Anaconda), PyQt 5.7 and sip 4.18.

I cannot reproduce the issue on a Linux machine with Python 3.6, PyQt 5.7.1 and sip 4.19.

(Unfortunately Python 3.6, PyQt 5.7.1 and sip 4.19 crash on Windows.)

**Comment by grinner** [comment]
This issue seems like it is fixed
